name: Build, test and deploy

on:
  - push
  - pull_request

jobs:
  test:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        python:
          - 2.7
          - 3.5
          - 3.6
          - 3.7
          - 3.8-dev
        include:
          - python: 3.8-dev
            continue: true
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.python}}
      - name: Install dependencies
        shell: bash
        run: ./script/install-dependencies.sh
      - name: Test
        continue-on-error: ${{matrix.continue}}
        shell: bash
        run: pytest --cov && codecov
        env:
          CODECOV_TOKEN: ${{secure.CODECOV_TOKEN}}

  documentation:
    name: Test documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Install dependencies
        run:
          - ./script/install-dependencies.sh
          - python -m pip install -r docs-requirements.txt
      - name: Build
        run: make --directory=docs html

  windows-installer:
    name: Build Windows installer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Install dependencies
        run:
          - ./script/install-dependencies.sh
          - python -m pip install pynsist==2.4
          - apt update -qq && apt install -qq -y nsis imagemagick inkscape
      - name: Build
        run: ./scripts/makeinstaller.sh
